name: Send submodule child1 updates to parent repo

on:
  push:
    branches: 
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with: 
          repository: Thomas9-Company/master-repo
          token: ${{ secrets.ORG_PAT }}
          submodules: true

      - name: Pull & update specific submodule (child1)
        run: |
          git submodule update --remote --recursive models/child1

      - name: Commit and push changes to master-repo
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"

          cd models/child1
          SUBMODULE_MSG=$(git log origin/main -1 --pretty=%B | tr '\n' ' ')
          cd -> /dev/null
          NEW_COMMIT_MSG="[child1 Update] => $SUBMODULE_MSG"

          git add models/child1
          git commit -m "$NEW_COMMIT_MSG" || echo "No changes to commit"
          git push